- name: Install Telnet for Memcached connection
  apt: 
    name: telnet

- name: Install memcached
  apt: 
    name: memcached

- name: Start memcached
  service:
    name: memcached
    enabled: yes
    state: restarted

- name: Check Memcached Version
  shell: sudo sh -c 'echo "Memcached $(apt-cache show memcached | grep Version | head -n1)" 1>> /data/logs/install_version.txt'

- name: Create a Memcached symbolic link
  file:
    src: /etc/memcached.conf
    dest: /data/config/memcached.conf
    state: link
