- name: Install Telnet for Memcached connection
  yum: 
    name: telnet
    
- name: Install memcached
  yum: 
    name: [memcached,libmemcached]

- name: Create a Memcached symbolic link
  file:
    src: /etc/sysconfig/memcached
    dest: /data/config/memcached.conf
    state: link

